language: node_js

node_js:
  - 0.6

before_script:
  - nvm install v0.6.17
  - nvm use v0.6.17
  - npm install jasmine-node jsdom jquery
  - cd Tests

script: ../node_modules/jasmine-node/bin/jasmine-node --coffee .

notifications:
  irc: "irc.freenode.net#xi-project"
