language: node_js

node_js:
  - 0.10

before_script:
  - npm install jasmine-node jsdom jquery
  - cd Tests

script: ../node_modules/jasmine-node/bin/jasmine-node --coffee .

notifications:
  irc: "irc.freenode.net#xi-project"
